#!/bin/sh
set -e

case "$1" in
    purge|remove|failed-upgrade|disappear|abort-install|abort-upgrade)
        echo "Removing diversion."
        dpkg-divert --package hairycandy-awesome --remove --rename \
                    --divert /usr/bin/awesome.real /usr/bin/awesome
    ;;
    upgrade)
    ;;
    *)
       echo "postrm called with unknown argument \`$1'" >&2
       exit 0
   ;;
esac

#DEBHELPER#

exit 0
